export { HomePage } from './Home/HomePage';
export { LoginPage } from './Auth/LoginPage';
export { EmployeesPage } from './Employees/EmployeesPage';
export { EmployeesFormAddPage } from './Employees/EmployeesFormAddPage';
export { EmployeeByDniPage } from './Employees/EmployeesByDniPage';
export { UpdateEmployeeByDni } from './Employees/UpdateEmployeeFormByDniPage';
export { UsersFormAddPage } from './Users/UsersFormAddPage';
export { UsersFormLockUnlockPage } from './Users/UsersFormLockUnlockPage';
export { UsersPage } from './Users/UsersPage';
